server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: donor-service
          uri: lb://donor-service
          predicates:
            - Path=/donor-service/**
          filters:
            - StripPrefix=1
        - id: blood-request-service
          uri: lb://blood-request-service
          predicates:
            - Path=/blood-request-service/**
          filters:
            - StripPrefix=1
        - id: donation-service
          uri: lb://donation-service
          predicates:
            - Path=/donation-service/**
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: '*'
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true


management:
  endpoints:
    web:
      exposure:
        include: health,info,routes
